#!/bin/bash
#
# split up the UK Biobank subjects
#
# ./shard-subjects-ukbiobank {beluga,graham,cedar}
# 
#

set() {
    # 'cast' the input stream to a set
    sort "$@" | uniq
}

complement() {
    # complement A B => compute A - B, sometimes written A \ B: everything in A that is *not* in B
    comm -23 <(set "$1") <(set "$2")
}

partition() {
server="$1"; shift
awk -v server="$server" '
server == "cedar" && NR%4 == 0
server == "graham" && NR%4 == 1
server == "beluga" && NR%4 == 2
server == "beluga" && NR%4 == 3
' "$1"
}

server="$1"
partition "$server" <(complement <(cut -f 1 -d ',' <(tail -n +2 selected_subjects.csv)) <(cut -f 2 -d ',' <(tail -n +2 duke_downloaded_subjects.csv)))
